[package]
name = "trololo"
version = "0.1.0"
edition = "2021"
uthors = "seralekseenko" 
repository = "https://github.com/seralekseenko/study_rust"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
