[package]
name = "my_collections"
version = "0.1.0"
edition = "2021"
authors = [ "seralekseenko" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
rand = "0.8.5"
statistical = "1.0.0"
